#!/bin/sh
# Open Brain — automated setup and upgrade script
# Usage:
#   Fresh install:  sh setup.sh --install <config-file>
#   Upgrade:        sh setup.sh --upgrade <vault-path>
#
# Config file is a simple KEY=VALUE file generated by the AI agent
# from the user's answers in Step 1 of SETUP-INSTRUCTIONS.md.
#
# Example config (quote values with spaces):
#   USER_FULL_NAME="Jane Smith"
#   USER_FIRST_NAME="Jane"
#   VAULT_PATH="~/Documents/Open Brain"
#   TIMEZONE="America/New_York"
#   BRIEFING_METHOD="slack"
#   SLACK_WORKSPACE="mycompany.slack.com"
#   SLACK_CHANNEL_ID="C01EXAMPLE1"
#   CALENDAR_ENABLED="true"

set -eu

SETUP_DIR="$(cd "$(dirname "$0")" && pwd)"

# ─────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "  $*"; }

# Substitute {{VARIABLE}} placeholders in a file using values from the config
substitute() {
    local src="$1" dst="$2"
    cp "$src" "$dst"

    sed -i '' \
        -e "s|{{USER_FULL_NAME}}|${USER_FULL_NAME}|g" \
        -e "s|{{USER_FIRST_NAME}}|${USER_FIRST_NAME}|g" \
        -e "s|{{USER_FIRST_NAME_SLUG}}|${USER_FIRST_NAME_SLUG}|g" \
        -e "s|{{VAULT_PATH}}|${VAULT_PATH}|g" \
        -e "s|{{VAULT_PATH_ESCAPED}}|${VAULT_PATH}|g" \
        -e "s|{{TIMEZONE}}|${TIMEZONE}|g" \
        -e "s|{{SLACK_WORKSPACE}}|${SLACK_WORKSPACE:-}|g" \
        -e "s|{{SLACK_CHANNEL_ID}}|${SLACK_CHANNEL_ID:-}|g" \
        -e "s|{{IMESSAGE_RECIPIENT}}|${IMESSAGE_RECIPIENT:-}|g" \
        -e "s|{{EMAIL_RECIPIENT}}|${EMAIL_RECIPIENT:-}|g" \
        "$dst"
}

# Auto-detect USER_FIRST_NAME from an existing vault's CLAUDE.md.
# The template line 3 reads: "{{USER_FIRST_NAME}}'s personal knowledge system — ..."
# which becomes "Jane's personal knowledge system — ..." after substitution.
# Echoes the name on stdout; empty string if not found.
detect_first_name() {
    local vault="$1"
    [ -f "$vault/CLAUDE.md" ] || { echo ""; return; }
    head -5 "$vault/CLAUDE.md" \
        | grep -oE "[A-Za-z]+'s personal knowledge system" \
        | head -1 \
        | sed "s/'s personal knowledge system//"
}

# Replace or append the Open Brain section in ~/.claude/CLAUDE.md.
# Used during upgrade. Handles both the current heading ("## Open Brain — ...'s knowledge system")
# and the legacy heading ("## Deep Context — Open Brain"). Backs up before editing.
# Requires USER_FIRST_NAME and VAULT_PATH to be set.
replace_or_append_global_section() {
    local global="$HOME/.claude/CLAUDE.md"
    local tmp_section="/tmp/ob-global-section.$$.md"
    local tmp_stripped="/tmp/ob-global-stripped.$$.md"

    mkdir -p "$HOME/.claude"
    substitute "$SETUP_DIR/templates/claude/global-claude-md-section.md" "$tmp_section"

    if [ ! -f "$global" ]; then
        cp "$tmp_section" "$global"
        info "Created ~/.claude/CLAUDE.md with Open Brain section."
        rm -f "$tmp_section"
        return
    fi

    cp "$global" "$global.bak.$(date +%s)"

    if grep -qE "^## Open Brain — |^## Deep Context — Open Brain" "$global"; then
        # Strip existing section (from its heading until the next `## ` heading or EOF)
        awk '
            BEGIN { in_section=0 }
            /^## Open Brain — / || /^## Deep Context — Open Brain/ { in_section=1; next }
            in_section && /^## / { in_section=0 }
            !in_section { print }
        ' "$global" > "$tmp_stripped"

        # Append the fresh section
        printf "\n" >> "$tmp_stripped"
        cat "$tmp_section" >> "$tmp_stripped"
        mv "$tmp_stripped" "$global"
        info "Rewrote Open Brain section in ~/.claude/CLAUDE.md."
    else
        printf "\n" >> "$global"
        cat "$tmp_section" >> "$global"
        info "Appended Open Brain section to ~/.claude/CLAUDE.md."
    fi

    rm -f "$tmp_section" "$tmp_stripped"
}

# Strip conditional blocks from a file, keeping only the matching method.
# Blocks look like:  <!-- IF BRIEFING_METHOD = slack --> ... <!-- END slack -->
strip_conditionals() {
    local file="$1" method="$2"

    # Remove non-matching briefing method blocks (content between markers)
    for m in slack imessage email file; do
        if [ "$m" != "$method" ]; then
            sed -i '' "/<!-- IF BRIEFING_METHOD = $m -->/,/<!-- END $m -->/d" "$file"
        fi
    done

    # Remove the comment markers from the kept block
    sed -i '' \
        -e "/<!-- IF BRIEFING_METHOD = $method -->/d" \
        -e "/<!-- END $method -->/d" \
        "$file"

    # Handle the SLACK conditional in CLAUDE.md
    if [ "$method" = "slack" ]; then
        sed -i '' \
            -e '/<!-- IF SLACK -->/d' \
            -e '/<!-- END SLACK -->/d' \
            "$file"
    else
        sed -i '' '/<!-- IF SLACK -->/,/<!-- END SLACK -->/d' "$file"
    fi

    # Handle the PHOTOS_INTEGRATION conditional — kept for native + adapt, stripped for skip
    if [ "${PHOTOS_INTEGRATION:-skip}" = "skip" ]; then
        sed -i '' '/<!-- IF PHOTOS_INTEGRATION -->/,/<!-- END PHOTOS_INTEGRATION -->/d' "$file"
    else
        sed -i '' \
            -e '/<!-- IF PHOTOS_INTEGRATION -->/d' \
            -e '/<!-- END PHOTOS_INTEGRATION -->/d' \
            "$file"
    fi
}

# Verify no leftover template markers remain in a file
verify_clean() {
    local file="$1"
    if grep -qE '\{\{[A-Z_]+\}\}' "$file" 2>/dev/null; then
        echo "WARNING: unfilled placeholders in $(basename "$file"):"
        grep -nE '\{\{[A-Z_]+\}\}' "$file"
        return 1
    fi
    if grep -qE '<!-- (IF BRIEFING_METHOD|IF SLACK|IF PHOTOS_INTEGRATION|END (slack|imessage|email|file|SLACK|PHOTOS_INTEGRATION)) -->' "$file" 2>/dev/null; then
        echo "WARNING: leftover conditional markers in $(basename "$file"):"
        grep -nE '<!-- (IF BRIEFING_METHOD|IF SLACK|IF PHOTOS_INTEGRATION|END (slack|imessage|email|file|SLACK|PHOTOS_INTEGRATION)) -->' "$file"
        return 1
    fi
    return 0
}

# ─────────────────────────────────────────────────────
# Load config
# ─────────────────────────────────────────────────────

load_config() {
    local config_file="$1"
    [ -f "$config_file" ] || die "Config file not found: $config_file"

    # Source the config (KEY=VALUE pairs)
    . "$config_file"

    # Validate required fields
    [ -n "${USER_FULL_NAME:-}" ] || die "USER_FULL_NAME is required in config"
    [ -n "${USER_FIRST_NAME:-}" ] || die "USER_FIRST_NAME is required in config"
    [ -n "${VAULT_PATH:-}" ] || die "VAULT_PATH is required in config"
    [ -n "${TIMEZONE:-}" ] || die "TIMEZONE is required in config"
    [ -n "${BRIEFING_METHOD:-}" ] || die "BRIEFING_METHOD is required in config"

    # Expand ~ in VAULT_PATH
    VAULT_PATH="$(eval echo "$VAULT_PATH")"
    export VAULT_PATH

    # Compute slug (lowercase, hyphenated)
    USER_FIRST_NAME_SLUG="$(echo "$USER_FIRST_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
    export USER_FIRST_NAME_SLUG

    # Validate briefing method
    case "$BRIEFING_METHOD" in
        slack)    [ -n "${SLACK_CHANNEL_ID:-}" ] || die "SLACK_CHANNEL_ID required for slack method" ;;
        imessage) [ -n "${IMESSAGE_RECIPIENT:-}" ] || die "IMESSAGE_RECIPIENT required for imessage method" ;;
        email)    [ -n "${EMAIL_RECIPIENT:-}" ] || die "EMAIL_RECIPIENT required for email method" ;;
        file)     ;;
        *)        die "Unknown BRIEFING_METHOD: $BRIEFING_METHOD (expected: slack, imessage, email, file)" ;;
    esac

    # Validate photos integration mode (default: skip)
    [ -n "${PHOTOS_INTEGRATION:-}" ] || PHOTOS_INTEGRATION="skip"
    case "$PHOTOS_INTEGRATION" in
        native|adapt|skip) ;;
        *) die "Unknown PHOTOS_INTEGRATION: $PHOTOS_INTEGRATION (expected: native, adapt, skip)" ;;
    esac
    export PHOTOS_INTEGRATION

    # Warn if native mode on non-macOS — photos pipeline won't work without Apple Photos
    if [ "$PHOTOS_INTEGRATION" = "native" ] && [ "$(uname -s)" != "Darwin" ]; then
        echo "  WARNING: PHOTOS_INTEGRATION=native but host is $(uname -s), not Darwin."
        echo "           The photos scripts will install but osxphotos is macOS-only."
        echo "           Consider PHOTOS_INTEGRATION=adapt instead."
    fi
}

# ─────────────────────────────────────────────────────
# Fresh Install
# ─────────────────────────────────────────────────────

do_install() {
    local config_file="$1"
    load_config "$config_file"

    echo "=== Open Brain — Fresh Install ==="
    echo "  Vault: $VAULT_PATH"
    echo "  User:  $USER_FIRST_NAME ($USER_FULL_NAME)"
    echo "  Briefing: $BRIEFING_METHOD"
    echo

    # Abort if vault already exists
    if [ -f "$VAULT_PATH/CLAUDE.md" ] && [ -d "$VAULT_PATH/notes/raw-daily-notes" ]; then
        die "Vault already exists at $VAULT_PATH. Use --upgrade instead."
    fi

    # Step 2: Create directories
    echo "Creating vault directories..."
    mkdir -p "$VAULT_PATH/notes/raw-daily-notes"
    mkdir -p "$VAULT_PATH/notes/historical-notes"
    mkdir -p "$VAULT_PATH/notes/transcripts"
    mkdir -p "$VAULT_PATH/notes/briefings"
    mkdir -p "$VAULT_PATH/projects"
    mkdir -p "$VAULT_PATH/Other Entities"
    mkdir -p "$VAULT_PATH/events"
    mkdir -p "$VAULT_PATH/Medical"
    mkdir -p "$VAULT_PATH/people"
    mkdir -p "$VAULT_PATH/places"
    mkdir -p "$VAULT_PATH/research"
    mkdir -p "$VAULT_PATH/scripts"
    mkdir -p "$VAULT_PATH/.githooks"
    mkdir -p "$VAULT_PATH/.claude/skills/open-brain-extract"
    mkdir -p "$VAULT_PATH/.obsidian"

    # Step 3: Copy and templatize files
    echo "Copying template files..."

    # Vault core files (need substitution + conditional stripping)
    substitute "$SETUP_DIR/templates/vault/CLAUDE.md" "$VAULT_PATH/CLAUDE.md"
    strip_conditionals "$VAULT_PATH/CLAUDE.md" "$BRIEFING_METHOD"

    substitute "$SETUP_DIR/templates/vault/OPEN-BRAIN-UPDATER.md" "$VAULT_PATH/OPEN BRAIN UPDATER.md"
    strip_conditionals "$VAULT_PATH/OPEN BRAIN UPDATER.md" "$BRIEFING_METHOD"

    substitute "$SETUP_DIR/templates/vault/Medical/Medical Info.md" "$VAULT_PATH/Medical/Medical Info.md"

    # Claude config files (need substitution)
    substitute "$SETUP_DIR/templates/claude/settings.local.json" "$VAULT_PATH/.claude/settings.local.json"
    substitute "$SETUP_DIR/templates/claude/skills/open-brain-extract/SKILL.md" "$VAULT_PATH/.claude/skills/open-brain-extract/SKILL.md"

    # Obsidian config (no substitution needed)
    for f in app.json appearance.json core-plugins.json graph.json; do
        cp "$SETUP_DIR/templates/vault/.obsidian/$f" "$VAULT_PATH/.obsidian/$f"
    done

    # Scripts (no substitution — work as-is)
    # Copy non-photos scripts first; photos scripts are handled conditionally below.
    for f in "$SETUP_DIR/templates/scripts/"*; do
        case "$(basename "$f")" in
            photos_*.py) : ;;  # skip — photos scripts installed conditionally
            *) cp "$f" "$VAULT_PATH/scripts/" ;;
        esac
    done
    chmod +x "$VAULT_PATH/scripts/"*.sh
    chmod +x "$VAULT_PATH/scripts/"*.py

    # Photos integration (conditional on PHOTOS_INTEGRATION != skip)
    if [ "$PHOTOS_INTEGRATION" != "skip" ]; then
        mkdir -p "$VAULT_PATH/Photos"
        mkdir -p "$VAULT_PATH/.claude/skills/what-did-i-see"
        mkdir -p "$VAULT_PATH/.claude/skills/photos-for-event"
        # photos_*.py contain {{USER_FIRST_NAME}} placeholders in their
        # docstrings — substitute() instead of cp().
        for f in "$SETUP_DIR/templates/scripts/photos_"*.py; do
            substitute "$f" "$VAULT_PATH/scripts/$(basename "$f")"
        done
        chmod +x "$VAULT_PATH/scripts/photos_"*.py
        substitute "$SETUP_DIR/templates/claude/skills/what-did-i-see/SKILL.md" \
            "$VAULT_PATH/.claude/skills/what-did-i-see/SKILL.md"
        substitute "$SETUP_DIR/templates/claude/skills/photos-for-event/SKILL.md" \
            "$VAULT_PATH/.claude/skills/photos-for-event/SKILL.md"
        substitute "$SETUP_DIR/templates/vault/Photos/README.md" "$VAULT_PATH/Photos/README.md"
        if [ "$PHOTOS_INTEGRATION" = "adapt" ]; then
            cp "$SETUP_DIR/templates/vault/Photos/WINDOWS-ADAPTATION.md" \
               "$VAULT_PATH/Photos/WINDOWS-ADAPTATION.md"
        fi
        info "Photos integration installed (mode: $PHOTOS_INTEGRATION)."
    fi

    # Generate AGENTS.md from the substituted CLAUDE.md
    ( cd "$VAULT_PATH" && python3 scripts/generate_agents_md.py >/dev/null )

    # Git hooks
    cp "$SETUP_DIR/templates/githooks/"* "$VAULT_PATH/.githooks/"
    chmod +x "$VAULT_PATH/.githooks/pre-commit"

    # .gitignore
    cp "$SETUP_DIR/dotgitignore" "$VAULT_PATH/.gitignore"

    # Create the user's people profile stub
    cat > "$VAULT_PATH/people/${USER_FIRST_NAME_SLUG}.md" << PROFILE
---
name: ${USER_FULL_NAME}
aliases: []
roles: [owner]
tier: 0
connection: "Vault owner"
---

## Relationship
- This is the vault owner's profile.
PROFILE

    # Verify no leftover placeholders
    echo "Verifying template substitution..."
    clean=true
    for f in "$VAULT_PATH/CLAUDE.md" "$VAULT_PATH/OPEN BRAIN UPDATER.md" \
             "$VAULT_PATH/Medical/Medical Info.md" "$VAULT_PATH/.claude/settings.local.json" \
             "$VAULT_PATH/.claude/skills/open-brain-extract/SKILL.md"; do
        if ! verify_clean "$f"; then
            clean=false
        fi
    done
    if [ "$clean" = "false" ]; then
        die "Template substitution incomplete — fix the warnings above"
    fi
    info "All templates clean."

    # Step 5: Global CLAUDE.md
    echo "Updating global ~/.claude/CLAUDE.md..."
    mkdir -p "$HOME/.claude"
    if [ -f "$HOME/.claude/CLAUDE.md" ]; then
        if grep -qE "^## Open Brain — |^## Deep Context — Open Brain" "$HOME/.claude/CLAUDE.md"; then
            info "Open Brain section already exists — skipping."
        else
            # Ensure newline before appending
            echo "" >> "$HOME/.claude/CLAUDE.md"
            substitute "$SETUP_DIR/templates/claude/global-claude-md-section.md" "/tmp/ob-global-section.md"
            cat "/tmp/ob-global-section.md" >> "$HOME/.claude/CLAUDE.md"
            rm -f "/tmp/ob-global-section.md"
            info "Appended Open Brain section."
        fi
    else
        substitute "$SETUP_DIR/templates/claude/global-claude-md-section.md" "$HOME/.claude/CLAUDE.md"
        info "Created ~/.claude/CLAUDE.md with Open Brain section."
    fi

    # Step 6: Scheduled task
    echo "Setting up scheduled task..."
    scheduled_task="$HOME/.claude/scheduled-tasks/open-brain-updater/SKILL.md"
    if [ -f "$scheduled_task" ] && ! grep -qF "$VAULT_PATH" "$scheduled_task"; then
        existing_cmd=$(grep -E '^sh ' "$scheduled_task" | head -1)
        echo "  WARNING: ~/.claude/scheduled-tasks/open-brain-updater/ already exists and"
        echo "           points at a different vault. Current command:"
        echo "             ${existing_cmd:-<could not parse SKILL.md>}"
        echo "           Skipping to avoid clobbering another Open Brain install."
        echo "           If you want this new vault to own the scheduled task, remove"
        echo "           the existing SKILL.md first and re-run setup."
    else
        mkdir -p "$HOME/.claude/scheduled-tasks/open-brain-updater"
        substitute "$SETUP_DIR/templates/scheduled-task/SKILL.md" "$scheduled_task"
        info "Created scheduled task at ~/.claude/scheduled-tasks/open-brain-updater/"
    fi

    # Step 7: Manifest + validation + git
    echo "Initializing manifest and validating..."
    touch "$VAULT_PATH/notes/.manifest"
    cd "$VAULT_PATH"
    python3 scripts/validate_open_brain.py --fresh-install
    python3 scripts/build_entity_index.py

    echo "Initializing git repository..."
    cd "$VAULT_PATH"
    git init
    git config core.hooksPath .githooks
    git add -A
    git commit -m "Initial Open Brain setup"

    echo
    echo "=== Setup Complete ==="
    echo
    echo "  Vault created at: $VAULT_PATH"
    echo
    echo "  Next steps:"
    echo "  1. Open Obsidian → Open folder as vault → $VAULT_PATH"
    echo "  2. Create your first daily note at notes/raw-daily-notes/$(date +%Y)/$(date +%m-%B)/$(date +%Y-%m-%d).md"
    if [ "$BRIEFING_METHOD" != "file" ]; then
        echo "  3. Connect your ${BRIEFING_METHOD} MCP in Claude Code, then add the permission"
        echo "     UUID to .claude/settings.local.json (see SETUP-INSTRUCTIONS.md Step 4)"
    fi
    echo "  4. Configure the open-brain-updater scheduled task (e.g., daily at 6 AM)"
    echo "  5. See examples/ in the setup directory for entity file format reference"
    if [ "$PHOTOS_INTEGRATION" = "native" ]; then
        echo "  6. Photos integration: run 'pip3 install osxphotos' and grant Full Disk"
        echo "     Access in System Settings → Privacy & Security → Full Disk Access."
        echo "     Then: python3 scripts/photos_update_index.py"
    elif [ "$PHOTOS_INTEGRATION" = "adapt" ]; then
        echo "  6. Photos integration: see Photos/WINDOWS-ADAPTATION.md for how to"
        echo "     implement a non-macOS backend that produces photos-index.json."
    fi
    echo
}

# ─────────────────────────────────────────────────────
# Upgrade
# ─────────────────────────────────────────────────────

do_upgrade() {
    local vault_path="$1"
    # Expand ~
    vault_path="$(eval echo "$vault_path")"

    [ -f "$vault_path/CLAUDE.md" ] || die "No CLAUDE.md found at $vault_path — is this an Open Brain vault?"
    [ -d "$vault_path/notes/raw-daily-notes" ] || die "No notes/raw-daily-notes/ found at $vault_path"

    echo "=== Open Brain — Upgrade ==="
    echo "  Vault: $vault_path"
    echo

    # Back up
    echo "Backing up existing files..."
    ts=$(date +%s)
    cp "$vault_path/CLAUDE.md" "$vault_path/CLAUDE.md.bak.$ts"
    if [ -f "$vault_path/OPEN BRAIN UPDATER.md" ]; then
        cp "$vault_path/OPEN BRAIN UPDATER.md" "$vault_path/OPEN BRAIN UPDATER.md.bak.$ts"
    fi
    info "Backups created with timestamp .$ts"

    # Copy scripts (overwrite). Photos scripts only if the vault has Photos/
    # (indicates photos integration is enabled on this vault).
    echo "Updating scripts..."
    mkdir -p "$vault_path/scripts"
    for f in "$SETUP_DIR/templates/scripts/"*; do
        case "$(basename "$f")" in
            photos_*.py)
                if [ -d "$vault_path/Photos" ]; then
                    cp "$f" "$vault_path/scripts/"
                fi
                ;;
            *) cp "$f" "$vault_path/scripts/" ;;
        esac
    done
    chmod +x "$vault_path/scripts/"*.sh
    chmod +x "$vault_path/scripts/"*.py 2>/dev/null || true
    if [ -d "$vault_path/Photos" ]; then
        info "Scripts updated (including photos scripts)."
    else
        info "Scripts updated (photos scripts skipped — no Photos/ dir)."
    fi

    # Copy git hooks (overwrite)
    echo "Updating git hooks..."
    mkdir -p "$vault_path/.githooks"
    cp "$SETUP_DIR/templates/githooks/"* "$vault_path/.githooks/"
    chmod +x "$vault_path/.githooks/pre-commit"
    info "Git hooks updated."

    # Configure git hooks path
    cd "$vault_path"
    git config core.hooksPath .githooks 2>/dev/null || true

    # Ensure manifest exists
    if [ ! -f "$vault_path/notes/.manifest" ]; then
        touch "$vault_path/notes/.manifest"
        info "Created empty manifest."
    fi

    # Ensure scheduled task exists
    task_dir="$HOME/.claude/scheduled-tasks/open-brain-updater"
    task_file="$task_dir/SKILL.md"
    if [ ! -f "$task_file" ]; then
        echo "Creating scheduled task..."
        mkdir -p "$task_dir"
        sed "s|{{VAULT_PATH}}|$vault_path|g" "$SETUP_DIR/templates/scheduled-task/SKILL.md" > "$task_file"
        info "Created scheduled task at $task_dir/"
    else
        info "Scheduled task already exists."
    fi

    # Update global ~/.claude/CLAUDE.md Open Brain section
    echo "Updating global ~/.claude/CLAUDE.md Open Brain section..."
    detected_name="$(detect_first_name "$vault_path")"
    if [ -n "$detected_name" ]; then
        # Set template vars needed by substitute(). Only USER_FIRST_NAME and VAULT_PATH
        # are referenced by the global section template; others are set to empty
        # to keep substitute()'s sed calls happy.
        USER_FIRST_NAME="$detected_name"
        USER_FULL_NAME="$detected_name"
        USER_FIRST_NAME_SLUG="$(echo "$detected_name" | tr '[:upper:]' '[:lower:]')"
        VAULT_PATH="$vault_path"
        TIMEZONE="${TIMEZONE:-}"
        SLACK_WORKSPACE="${SLACK_WORKSPACE:-}"
        SLACK_CHANNEL_ID="${SLACK_CHANNEL_ID:-}"
        IMESSAGE_RECIPIENT="${IMESSAGE_RECIPIENT:-}"
        EMAIL_RECIPIENT="${EMAIL_RECIPIENT:-}"
        info "Detected user first name: $detected_name"
        replace_or_append_global_section
    else
        info "Could not auto-detect user first name from vault CLAUDE.md."
        info "Skipping global section update. Follow U6 in SETUP-INSTRUCTIONS.md to update manually."
    fi

    # Validate and build index
    echo "Running validation..."
    cd "$vault_path"
    python3 scripts/validate_open_brain.py || true
    python3 scripts/build_entity_index.py

    echo
    echo "=== Upgrade Complete ==="
    echo
    echo "  Automated updates applied:"
    echo "    - Scripts and git hooks refreshed"
    echo "    - Entity index regenerated"
    if [ -n "$detected_name" ]; then
        echo "    - Global ~/.claude/CLAUDE.md Open Brain section rewritten"
    fi
    echo
    echo "  MANUAL REVIEW NEEDED (files that may have user customizations):"
    echo
    echo "  1. Vault CLAUDE.md ($vault_path/CLAUDE.md)"
    echo "     Compare against templates/vault/CLAUDE.md. Add if missing:"
    echo "       - Entity Index section (after File Locations table)"
    echo "       - Validation section (after Manifest section)"
    echo "       - 'Today's raw note' note under Step 2 of 'How to Find Information'"
    echo "       - Photos section (if photos integration is enabled)"
    echo
    echo "  2. OPEN BRAIN UPDATER.md ($vault_path/OPEN BRAIN UPDATER.md)"
    echo "     Compare against templates/vault/OPEN-BRAIN-UPDATER.md. Add if missing:"
    echo "       - Step 2a references entities-index.md (not manual ls/head scanning)"
    echo "       - Step 2f (Validate Vault Structure) after Step 2e"
    echo "       - Step 4 includes re-running validation"
    echo
    echo "  Backups saved as .bak.$ts files. Templates at $SETUP_DIR/templates/vault/"
    echo
}

# ─────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────

usage() {
    echo "Usage:"
    echo "  sh setup.sh --install <config-file>   Fresh install from config"
    echo "  sh setup.sh --upgrade <vault-path>    Upgrade existing vault"
    echo
    echo "Config file format (KEY=VALUE, one per line):"
    echo "  USER_FULL_NAME=Jane Smith"
    echo "  USER_FIRST_NAME=Jane"
    echo "  VAULT_PATH=~/Documents/Open Brain"
    echo "  TIMEZONE=America/New_York"
    echo "  BRIEFING_METHOD=slack"
    echo "  SLACK_CHANNEL_ID=C01EXAMPLE1"
    echo "  SLACK_WORKSPACE=mycompany.slack.com"
}

case "${1:-}" in
    --install)
        [ -n "${2:-}" ] || { usage; die "Missing config file argument"; }
        do_install "$2"
        ;;
    --upgrade)
        [ -n "${2:-}" ] || { usage; die "Missing vault path argument"; }
        do_upgrade "$2"
        ;;
    *)
        usage
        exit 1
        ;;
esac
